package modules

import (
	"github.com/QuestScreen/api/server"
	"github.com/QuestScreen/api/web/config"
)

// ConfigWidgetGenerator generates a config item's UI widget.
type ConfigWidgetGenerator func(ctx server.Context) config.Widget

// ConfigItem describes a configuration item of a module.
// An instance can be generated with the contained generator.
//
// This type is used by code autogenerated with qs-build.
type ConfigItem struct {
	// The constructor function for the configuration item's widget.
	Constructor ConfigWidgetGenerator
	// Name is the name of this config item and will be displayed in the UI.
	Name string
}
